version: '3'

services:
  app:
    image: 'spring-notes-app:latest'
    build:
      context: .
    container_name: app
    restart: on-failure
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/springnote
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: 'mysql:latest'
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=springnote